FROM flink:1.18-scala_2.12-java11

# Download Flink SQL Kafka connector
RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-sql-connector-kafka/3.1.0-1.18/flink-sql-connector-kafka-3.1.0-1.18.jar

# Download Flink Avro Confluent connector
RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/1.18.0/flink-sql-avro-confluent-registry-1.18.0.jar

# Download JDBC connector for PostgreSQL sink (3.2.0 supports SinkV2)
RUN wget -P /opt/flink/lib https://repo1.maven.org/maven2/org/apache/flink/flink-connector-jdbc/3.2.0-1.18/flink-connector-jdbc-3.2.0-1.18.jar && \
    wget -P /opt/flink/lib https://jdbc.postgresql.org/download/postgresql-42.7.1.jar
