[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tablewatch"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "pydantic>=2.0",
  "networkx>=3.2",
  "leidenalg>=0.10",
  "pandas>=2.2",
  "scikit-learn>=1.4",
  "confluent-kafka[avro]>=2.13.2",
  "pydantic-avro>=0.7.0",
  "psycopg2>=2.9.11",
  "redis>=7.3.0",
  "fastavro>=1.9"
]

[tool.setuptools.packages.find]
where = ["src"]
